zend_extension=xdebug

[xdebug]
xdebug.mode=debug
xdebug.start_with_request=yes

; Den här adressen pekar tillbaka på din host-maskin
xdebug.client_host=host.docker.internal
xdebug.client_port=9003

; Valfritt logg (bra om något strular)
xdebug.log=/tmp/xdebug.log